#!/bin/bash
set -e

echo "Creating User"
echo $POSTGRES_USER
echo $POSTGRES_DB
echo $DB_USER
echo $DB_PASSWORD

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" $POSTGRES_DB <<-EOSQL
    CREATE USER $DB_USER;
    ALTER USER $DB_USER WITH ENCRYPTED PASSWORD '$DB_PASSWORD';
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $DB_USER;
    GRANT USAGE ON SCHEMA stag TO $DB_USER;
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA stag TO $DB_USER;
EOSQL
